services:
    mysql:
        image: mysql:8.0.31
        command: --default-authentication-plugin=mysql_native_password --sql-mode="NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION" --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: mensa
            MYSQL_USER: mensa
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
        volumes:
            - ./docker/mysql/schemas:/docker-entrypoint-initdb.d
