---
- name: phpunit
  hosts: localhost
  connection: local
  tasks:
    - name: render laravel dot env file
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        lstrip_blocks: true
        trim_blocks: true
      loop:
        - { src: "{{ playbook_dir }}/../roles/deploy_hooks/templates/env.j2", dest: "{{ playbook_dir }}/../../.env" }
